<!--- 
	  
  Copyright (c) 2006, Chris Scott, Matt Woodward, Adam Wayne Lehman, Dave Ross
  All rights reserved.
	
  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at
  
       http://www.apache.org/licenses/LICENSE-2.0
  
  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.

  $Id$

--->

<cfcomponent displayname="User" extends="net.litepost.component.NullableComponent"
	output="false" hint="A bean which models the  form.">

<!--- This bean was generated by the Rooibos Generator with the following template:
Bean Name: 
Path to Bean: 
Extends: 
Call super.init(): false
Create cfproperties: false
Bean Template:
	userID numeric 0
	firstName string 
	lastName string 
	email string 
	userName string 
	password string 
	role string
Create getMemento method: false
Create setMemento method: false
Create setStepInstance method: false
Create validate method: false
Create validate interior: false
Date Format: MM/DD/YYYY
--->

	<!---
	PROPERTIES
	--->
	<cfset variables.instance = StructNew() />
	<cfset variables.instance.Authenticated = false />

	<!---
	INITIALIZATION / CONFIGURATION
	--->
	<cffunction name="init" access="public" returntype="net.litepost.component.user.User" output="false">
		<cfargument name="userID" type="numeric" required="false" default="0" />
		<cfargument name="firstName" type="string" required="false" default="" />
		<cfargument name="lastName" type="string" required="false" default="" />
		<cfargument name="email" type="string" required="false" default="" />
		<cfargument name="userName" type="string" required="false" default="" />
		<cfargument name="password" type="string" required="false" default="" />
		<cfargument name="role" type="string" required="false" default="" />
		
		<!--- init parent --->
		<cfset super.init() />
		
		<!--- run setters --->
		<cfset setUserID(arguments.userID) />
		<cfset setFirstName(arguments.firstName) />
		<cfset setLastName(arguments.lastName) />
		<cfset setEmail(arguments.email) />
		<cfset setUserName(arguments.userName) />
		<cfset setPassword(arguments.password) />
		<cfset setRole(arguments.role) />

		<cfreturn this />
 	</cffunction>

	<!---
	ACCESSORS
	--->
	<cffunction name="setUserID" access="public" returntype="void" output="false">
		<cfargument name="userID" type="numeric" required="true" />
		<cfset variables.instance.userID = trim(arguments.userID) />
	</cffunction>
	<cffunction name="getUserID" access="public" returntype="numeric" output="false">
		<cfreturn variables.instance.userID />
	</cffunction>

	<cffunction name="setFirstName" access="public" returntype="void" output="false">
		<cfargument name="firstName" type="string" required="true" />
		<cfset variables.instance.firstName = arguments.firstName />
	</cffunction>
	<cffunction name="getFirstName" access="public" returntype="string" output="false">
		<cfreturn variables.instance.firstName />
	</cffunction>

	<cffunction name="setLastName" access="public" returntype="void" output="false">
		<cfargument name="lastName" type="string" required="true" />
		<cfset variables.instance.lastName = arguments.lastName />
	</cffunction>
	<cffunction name="getLastName" access="public" returntype="string" output="false">
		<cfreturn variables.instance.lastName />
	</cffunction>

	<cffunction name="setEmail" access="public" returntype="void" output="false">
		<cfargument name="email" type="string" required="true" />
		<cfset variables.instance.email = arguments.email />
	</cffunction>
	<cffunction name="getEmail" access="public" returntype="string" output="false">
		<cfreturn variables.instance.email />
	</cffunction>

	<cffunction name="setUserName" access="public" returntype="void" output="false">
		<cfargument name="userName" type="string" required="true" />
		<cfset variables.instance.userName = arguments.userName />
	</cffunction>
	<cffunction name="getUserName" access="public" returntype="string" output="false">
		<cfreturn variables.instance.userName />
	</cffunction>

	<cffunction name="setPassword" access="public" returntype="void" output="false">
		<cfargument name="password" type="string" required="true" />
		<cfset variables.instance.password = arguments.password />
	</cffunction>
	<cffunction name="getPassword" access="public" returntype="string" output="false">
		<cfreturn variables.instance.password />
	</cffunction>

	<cffunction name="setRole" access="public" returntype="void" output="false">
		<cfargument name="role" type="string" required="true" />
		<cfset variables.instance.role = arguments.role />
	</cffunction>
	<cffunction name="getRole" access="public" returntype="string" output="false">
		<cfreturn variables.instance.role />
	</cffunction>

	<cffunction name="setAuthenticated" access="public" output="false" returntype="void" hint="I set the IsAuthenticated in this instance">
		<cfargument name="Authenticated" type="boolean" required="true" />
		<cfset variables.instance.Authenticated = arguments.Authenticated />
	</cffunction>
	<cffunction name="isAuthenticated" access="public" output="false" returntype="boolean" hint="I retrieve the IsAuthenticated from this instance">
		<cfreturn variables.instance.Authenticated />
	</cffunction>

</cfcomponent>